version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpwd
      - MYSQL_DATABASE=gogs
    volumes:
      - /DB/gogs:/var/lib/mysql
  gogs:
    build: .
    environment:
      - RUN_USER=git
      - USER=git
    volumes:
      - /shared/misc/gogs_conf:/go/src/github.com/gogits/gogs/custom/conf
      - /shared/git/gogs:/srv/git
      - /shared/logs/gogs:/go/src/github.com/gogits/gogs/log
    ports:
      - "10022:10022"
      - "10080:10080"
    depends_on:
      - db
