---
version: '3'
services:
  minecraft:
    image: minecraft
    build:
      context: .
    volumes:
      - "/home/vmonteco/Volumes/minecraft_world:/home/minecraft/world"
    ports:
      - "25565:25565"
