version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpwd
      - MYSQL_DATABASE=gogs
    volumes:
      - gogs_db:/var/lib/mysql
  gogs:
    build: .
    environment:
      - RUN_USER=git
      - USER=git
    volumes:
      - gogs_conf:/go/src/github.com/gogits/gogs/custom/conf
      - gogs_git:/srv/git
      - gogs_logs:/go/src/github.com/gogits/gogs/log
    ports:
      - "10022:22"
      - "10080:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  gogs_db:
  gogs_git:
  gogs_conf:
  gogs_logs:
