#!/usr/bin/env sh

set -x

MACHINE_NAME=Char
VOLUME_NAME=hatchery
VOLUME_HOST_PATH=$(pwd)/hatchery
VOLUME_GUEST_PATH=/hatchery

if [[ $(docker-machine status $MACHINE_NAME ) == "Running" ]]; then
   echo "Stopping $MACHINE_NAME docker machine.";
   docker-machine stop $MACHINE_NAME;
   echo "$MACHINE_NAME docker machine stopped.";
fi

mkdir $VOLUME_HOST_PATH

echo "Adding volume to VM :"
VBoxManage sharedfolder add $MACHINE_NAME --name $VOLUME_NAME --hostpath $VOLUME_HOST_PATH

echo "Restarting machine :"
docker-machine start $MACHINE_NAME

echo "Mounting volume in docker machine :"
docker-machine ssh $MACHINE_NAME "sudo mkdir $VOLUME_GUEST_PATH; sudo mount -t vboxsf $VOLUME_NAME $VOLUME_GUEST_PATH"
echo "Done."

