#!/usr/bin/env sh

# NB : hatchery directory must be empty
docker run --restart "on-failure" -e MYSQL_ROOT_PASSWORD=Kerrigan -e MYSQL_DATABASE=zerglings -d -v /hatchery:/var/lib/mysql  -p 32775:3306 --name spawning-pool mysql

# To connect : mysql -uroot -p'Kerrigan' -h $(docker-machine ip Char) -P 32775
