#!/usr/bin/env sh

docker-machine ssh Char "docker service create -e RABBITMQ_DEFAULT_USER='user' -e RABBITMQ_DEFAULT_PASS='pwd' --name orbital-command --log-driver journald --network overmind rabbitmq"
