#!/usr/bin/env sh

docker-machine ssh Char "docker service create --name orbital-command --network overmind -d -e RABBITMQ_DEFAULT_USER='user' -e RABBITMQ_DEFAULT_PASS='password' --publish published=8080,target=15672 rabbitmq:3-management"
